POST http://localhost:3001/blogs
Content-Type: application/json

{
    "title": "Esto es un blog creado por un POST",
    "body": "Aliquam sit amet suscipit urna, eget consequat purus. Donec dolor enim, tincidunt et metus id, auctor faucibus velit. Aliquam pharetra neque id lorem commodo, eu auctor ante commodo. Vivamus ut lacus dictum, malesuada erat et, posuere libero. Fusce accumsan aliquam sodales. Curabitur id nunc pharetra, molestie neque id, lobortis risus. Ut mattis, augue non semper hendrerit, ligula nisi placerat lacus, eu laoreet dui ante eget turpis. Etiam convallis, purus a hendrerit consequat, mauris justo dignissim neque, sit amet sollicitudin lectus mi in urna. Etiam vestibulum eros augue, in viverra sapien aliquet nec. Ut vulputate arcu sed purus sollicitudin, vitae varius erat ullamcorper. Nam porta feugiat eros, eu ornare lorem pharetra vel.",
    "authorId": "61d890f6251afdaaed1c30e7"
}

### 400
POST http://localhost:3001/blogs
Content-Type: application/json

{
    "title": "Esto es un blog creado por un POST",
    "body": "",
    "author": "Dagore"
}